### ISSUE TITLE
A question about preact/hooks on cdn.pika

### ISSUE THREAD

**Issue by jessehattabaugh** [lukejacksonn/blog#1]
Sorry for asking you this here, but I quit Twitter and I don't know your email address.

I'm trying to build a Pika CDN powered site with `preact` and `htm` like you have here:

https://github.com/lukejacksonn/blog/blob/ce3a74d368a8b9ee741c46b865e159539cbdc92c/index.js#L6

I've got a component successfully mounting. But when I tried to `import { useEffect } from 'https://cdn.pika.dev/preact@10.3.3/hooks';` so I can `useEffect(() => {}, [])` I get an error:

![image](https://user-images.githubusercontent.com/17991/80297747-f070d200-873a-11ea-9c19-c0bbdb9f55b4.png)

which stacktraces to some unhelpfully minified code

![image](https://user-images.githubusercontent.com/17991/80297786-4fcee200-873b-11ea-8be4-122699173e47.png)

I'm kinda new to the ESM game so I'm a bit lost when it comes to debugging this. I searched GitHub for `cdn.pika.dev/preact` and I found your code that seems to work just fine. I was wondering if you could take a look at my code and tell me what I'm doing wrong.

https://github.com/jessehattabaugh/sandbox/blob/cb80479d0121b2698d5a235d3c0c12e9e7dcf491/world.js#L11

If you can give me any pointers about how to get sourcemaps to unminified code working for cdn.pika that would also be appreciated. I'd really like to avoid a build step for a change. 

Your former Twitter follower,
Jesse Hattabaugh

**Comment by jessehattabaugh** [comment]
Nevermind! I just needed some sleep. I came back and realized that when you `render()` you pass an `html'<${app} />'` as the first argument. I was calling my `World()` component instead. https://github.com/jessehattabaugh/sandbox/blob/06221e83c487d09a50116a72fae270428c852909/index.js#L8 I was calling it because passing the function component itself wasn't working. ::shrug::

Anyway, thanks for the code to crib from. This project looks awesome. I don't know if you're involved in any of these libs, but they are also awesome! I love living in the future!

**Comment by lukejacksonn** [comment]
Hey Jesse! 👋 only just seen this! Been a busy week for me. Glad you managed to get it sorted in the end. Something similar happened to me the other day on perflink.. https://github.com/lukejacksonn/perflink/pull/30.

I'm still not sure what it was but decided to vendor my scripts for now so it won't happen again without me knowing about it at least. Still experimenting 🔬
